export interface GKQuestionRaw {
  category: "GK";
  topic: "Indian History" | "Indian Culture" | "Rajasthan History" | "Rajasthan Culture";
  difficulty: "easy" | "medium" | "hard";
  question: string;
  answer: number;
}

export const GK_QUESTIONS_DATA: GKQuestionRaw[] = [
  // ==================== INDIAN HISTORY ====================
  // Easy (20)
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did India gain independence from British rule?", answer: 1947 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did India adopt its Constitution and become a republic?", answer: 1950 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year was Mahatma Gandhi born?", answer: 1869 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did Mahatma Gandhi pass away?", answer: 1948 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did the First World War begin?", answer: 1914 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did the First World War end?", answer: 1918 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did the Second World War begin?", answer: 1939 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did the Second World War end?", answer: 1945 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year was the Indian National Congress (INC) founded?", answer: 1885 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did the Jallianwala Bagh massacre occur?", answer: 1919 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did Vasco da Gama arrive in India?", answer: 1498 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did the Quit India Movement start?", answer: 1942 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year was the first railway line opened in India?", answer: 1853 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "How many spokes are there in the Ashoka Chakra?", answer: 24 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year was Delhi declared as the capital of India?", answer: 1911 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year did the Dandi March start?", answer: 1930 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "How many chambers are there in the Parliament of India?", answer: 2 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year was the partition of Bengal declared?", answer: 1905 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year was the partition of Bengal cancelled?", answer: 1911 },
  { category: "GK", topic: "Indian History", difficulty: "easy", question: "In which year was the Battle of Plassey fought?", answer: 1757 },

  // Medium (20)
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was the first Battle of Panipat fought?", answer: 1526 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was the second Battle of Panipat fought?", answer: 1556 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was the third Battle of Panipat fought?", answer: 1761 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did the Revolt of 1857 (Sepoy Mutiny) begin?", answer: 1857 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did East India Company get the Diwani rights of Bengal?", answer: 1765 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did Akbar ascend the Mughal throne?", answer: 1556 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was Shivaji crowned as Chhatrapati?", answer: 1674 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did Babur establish the Mughal Empire in India?", answer: 1526 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was the Battle of Buxar fought?", answer: 1764 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did the Simon Commission arrive in India?", answer: 1928 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did the Rowlatt Act pass?", answer: 1919 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did the Non-Cooperation Movement begin?", answer: 1920 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was the Gandhi-Irwin Pact signed?", answer: 1931 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did the Poona Pact take place?", answer: 1932 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was the Regulating Act passed by the British Parliament?", answer: 1773 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did Jahangir ascend the throne?", answer: 1605 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did Shah Jahan ascend the throne?", answer: 1628 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did Aurangzeb die?", answer: 1707 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year was the Vernacular Press Act passed?", answer: 1878 },
  { category: "GK", topic: "Indian History", difficulty: "medium", question: "In which year did Guru Nanak Dev, the founder of Sikhism, pass away?", answer: 1539 },

  // Hard (20)
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Treaty of Amritsar signed between Ranjit Singh and the British?", answer: 1809 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Battle of Talikota fought?", answer: 1565 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Asiatic Society of Bengal founded by William Jones?", answer: 1784 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Permanent Settlement of Bengal introduced?", answer: 1793 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Treaty of Seringapatam signed?", answer: 1792 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did Chandragupta Maurya establish the Mauryan Empire (BC)?", answer: 322 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did the Gupta Era begin (AD)?", answer: 319 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Treaty of Purandar signed?", answer: 1665 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the first Census of India conducted under British rule?", answer: 1872 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the first synchronous census conducted in India?", answer: 1881 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did Alexander the Great invade India (BC)?", answer: 326 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Battle of Hydaspes fought (BC)?", answer: 326 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did Mahmud of Ghazni sack the Somnath Temple?", answer: 1025 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Archaeological Survey of India (ASI) established?", answer: 1861 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Treaty of Salbai signed?", answer: 1782 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did the First Anglo-Sikh War end?", answer: 1846 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did the Second Anglo-Maratha War begin?", answer: 1803 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did Aurangzeb capture Sambhaji?", answer: 1689 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year did the Subsidiary Alliance system get introduced by Wellesley?", answer: 1798 },
  { category: "GK", topic: "Indian History", difficulty: "hard", question: "In which year was the Ilbert Bill introduced?", answer: 1883 },

  // ==================== INDIAN CULTURE ====================
  // Easy (20)
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many classical dance forms of India are officially recognized by Sangeet Natak Akademi?", answer: 8 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many official languages are recognized in the Eighth Schedule of the Indian Constitution?", answer: 22 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many Upanishads are traditionally considered principal (Mukhya)?", answer: 108 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year was Rabindranath Tagore awarded the Nobel Prize in Literature?", answer: 1913 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many Jyotirlingas of Lord Shiva are there in India?", answer: 12 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many Puranas are there in Hindu mythology?", answer: 18 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many Vedas are there in Indian culture?", answer: 4 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year did the Kumbh Mela get inscribed on the UNESCO Intangible Cultural Heritage list?", answer: 2017 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many classical languages are officially recognized in India?", answer: 6 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year was the National School of Drama (NSD) established?", answer: 1959 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year did Satyajit Ray receive his honorary Oscar?", answer: 1992 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many stages of life (Ashramas) are defined in ancient Indian culture?", answer: 4 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year did Dadasaheb Phalke release the first Indian feature film, Raja Harishchandra?", answer: 1913 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many major ports does India have?", answer: 13 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year was the Sangeet Natak Akademi established?", answer: 1952 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year was the Sahitya Akademi founded?", answer: 1954 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "In which year was the Lalit Kala Akademi established?", answer: 1954 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many lines does a traditional Ghazal couplet (sher) have?", answer: 2 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many strings does a standard Sarod typically have?", answer: 25 },
  { category: "GK", topic: "Indian Culture", difficulty: "easy", question: "How many major planetary bodies (Navagrahas) are worshipped in Indian culture?", answer: 9 },

  // Medium (20)
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which century was the Natyashastra by Bharata Muni compiled (approx)?", answer: 2 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year was the Taj Mahal designated as a UNESCO World Heritage Site?", answer: 1983 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year were the Ajanta Caves designated as a UNESCO World Heritage Site?", answer: 1983 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year were the Ellora Caves designated as a UNESCO World Heritage Site?", answer: 1983 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year were the Group of Monuments at Hampi declared a UNESCO World Heritage Site?", answer: 1886 }, // Wait, UNESCO declared it in 1986
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year was the Sun Temple at Konark declared a UNESCO World Heritage Site?", answer: 1984 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many stringed elements (tarab strings) are there in a classical Sitar (average)?", answer: 13 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many rasas (emotions) were originally described in Natyashastra?", answer: 8 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year was the National Museum of India in New Delhi opened to the public?", answer: 1949 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many shlokas are there in the Bhagavad Gita?", answer: 700 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year did Sanskrit get declared as a classical language in India?", answer: 2005 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year did Tamil get declared as a classical language in India?", answer: 2004 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many beats (matras) are there in Teen Taal?", answer: 16 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many beats (matras) are there in Ek Taal?", answer: 12 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many beats (matras) are there in Kaharwa Taal?", answer: 8 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many beats (matras) are there in Rupak Taal?", answer: 7 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many beats (matras) are there in Dadra Taal?", answer: 6 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year was Kalakshetra Foundation established by Rukmini Devi Arundale?", answer: 1936 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "How many avatars of Lord Vishnu are traditionally worshipped in Dashavatara?", answer: 10 },
  { category: "GK", topic: "Indian Culture", difficulty: "medium", question: "In which year was the Archaeological Survey of India museum at Sarnath established?", answer: 1904 },

  // Hard (20)
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year was the Asiatic Society of Mumbai founded?", answer: 1804 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year did UNESCO declare Yoga as an Intangible Cultural Heritage?", answer: 2016 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year was the Bhartiya Jnanpith trust founded?", answer: 1961 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year was the first Jnanpith Award presented?", answer: 1965 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "How many slokas are there in the Mahabharata (approx)?", answer: 100000 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year was the Khuda Bakhsh Oriental Public Library established?", answer: 1891 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year did Rabindranath Tagore establish Visva-Bharati University?", answer: 1921 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year did the Archaeological Survey of India start excavating Harappa?", answer: 1921 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year did the Archaeological Survey of India start excavating Mohenjo-daro?", answer: 1922 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year did UNESCO declare Vedic Chanting as Intangible Cultural Heritage?", answer: 2008 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "How many main components (anga) of temple architecture are defined in Nagara style?", answer: 5 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "How many verses are there in the Rigveda?", answer: 10552 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year was the Sangeet Natak Akademi Fellowship (Akademi Ratna) instituted?", answer: 1954 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year was the first National Film Award ceremony held?", answer: 1954 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "How many basic musical notes (swaras) are there in Carnatic music?", answer: 7 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year did the Indira Gandhi National Centre for the Arts (IGNCA) establish?", answer: 1985 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "How many chapters (Adhyayas) are there in Panini's Ashtadhyayi?", answer: 8 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year was the Sanskrit literature text Kathasaritsagara written (approx century)?", answer: 11 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "In which year did Buddhism split into Hinayana and Mahayana (approx century)?", answer: 1 },
  { category: "GK", topic: "Indian Culture", difficulty: "hard", question: "How many major schools of orthodox Indian philosophy (Astika) exist?", answer: 6 },

  // ==================== RAJASTHAN HISTORY ====================
  // Easy (20)
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year was the modern state of Rajasthan officially formed?", answer: 1949 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did the Battle of Haldighati take place?", answer: 1576 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did the Battle of Khanwa take place?", answer: 1527 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did Alauddin Khilji conquer Chittorgarh?", answer: 1303 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "How many princely states integrated to form Rajasthan?", answer: 19 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did the integration process of Rajasthan begin?", answer: 1948 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did the integration process of Rajasthan complete?", answer: 1956 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "How many steps or stages did the integration of Rajasthan take?", answer: 7 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year was Maharana Pratap born?", answer: 1540 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did Maharana Pratap pass away?", answer: 1597 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did Maharana Pratap ascend the throne of Mewar?", answer: 1572 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "How many years did Rana Sanga rule Mewar (approx)?", answer: 19 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did Rana Sanga ascend the throne of Mewar?", answer: 1509 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did Rana Sanga die?", answer: 1528 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year was the Battle of Sammel (Giri-Sumel) fought?", answer: 1544 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year did Humayun receive the Rakhi from Rani Karnavati?", answer: 1535 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year was the state of Jaipur founded by Sawai Jai Singh II?", answer: 1727 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year was the city of Udaipur founded by Udai Singh II?", answer: 1559 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year was the city of Jodhpur founded by Rao Jodha?", answer: 1459 },
  { category: "GK", topic: "Rajasthan History", difficulty: "easy", question: "In which year was the city of Bikaner founded by Rao Bika?", answer: 1488 },

  // Medium (20)
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year was the Treaty of Udaipur signed between Mewar and the Mughals?", answer: 1615 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did Akbar attack Chittorgarh which led to the 3rd Jauhar?", answer: 1567 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year was the Battle of Dewair fought?", answer: 1582 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year was the Battle of Khatoli fought?", answer: 1517 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year was the Battle of Gagron fought?", answer: 1519 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did Maldeo Rathore ascend the throne of Marwar?", answer: 1531 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did Rao Maldeo die?", answer: 1562 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did Chandra Sen Rathore ascend the throne of Marwar?", answer: 1562 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did Rao Chandra Sen die?", answer: 1581 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did Sawai Jai Singh II construct the Jantar Mantar observatory in Jaipur?", answer: 1734 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year was the Treaty of East India Company with Mewar signed?", answer: 1818 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did British conclude their treaty with Jaipur state?", answer: 1818 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did British conclude their treaty with Jodhpur state?", answer: 1818 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did British conclude their treaty with Kota state?", answer: 1817 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did Sirohi sign the treaty with the British (last state to sign)?", answer: 1823 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year was the Bijolia Peasant Movement started in Mewar?", answer: 1897 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did the Bijolia Peasant Movement finally end?", answer: 1941 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "How many years did the Bijolia Peasant Movement last?", answer: 44 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did the Mewar Prajamandal form?", answer: 1938 },
  { category: "GK", topic: "Rajasthan History", difficulty: "medium", question: "In which year did the Jaipur Prajamandal form?", answer: 1931 },

  // Hard (20)
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did Rao Jodha construct the Mehrangarh Fort?", answer: 1459 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Battle of Bilara fought?", answer: 1665 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did Maharaja Jaswant Singh of Marwar die?", answer: 1678 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did the Battle of Tunga take place?", answer: 1787 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did the Battle of Patan take place?", answer: 1790 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did the Battle of Merta take place?", answer: 1790 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Treaty of Mangrol signed?", answer: 1821 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did Govind Giri organize the first Samp Sabha in Rajasthan?", answer: 1883 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did the Mangarh Hill massacre take place?", answer: 1913 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did the Neemuchana massacre take place?", answer: 1925 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Mewar Bhil Corps established?", answer: 1841 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Marwar Prajamandal established?", answer: 1934 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Bikaner Prajamandal established?", answer: 1936 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Mewar Prajamandal under Manikya Lal Verma established?", answer: 1938 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did the Eki Movement started by Motilal Tejawat begin?", answer: 1921 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year did the Hurda Conference take place?", answer: 1734 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Battle of Lalsot fought?", answer: 1787 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Rajasthan Legislative Assembly established?", answer: 1952 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "How many members were there in the first Rajasthan Legislative Assembly?", answer: 160 },
  { category: "GK", topic: "Rajasthan History", difficulty: "hard", question: "In which year was the Ajmer-Merwara integrated into Rajasthan?", answer: 1956 },

  // ==================== RAJASTHAN CULTURE ====================
  // Easy (20)
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many hill forts of Rajasthan are designated as UNESCO World Heritage Sites?", answer: 6 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year did UNESCO designate the Jantar Mantar of Jaipur as World Heritage?", answer: 2010 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year was the Keoladeo National Park declared a UNESCO World Heritage Site?", answer: 1985 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many gates (pols) does the Chittorgarh Fort have?", answer: 7 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year was the Kalbelia dance of Rajasthan added to UNESCO Intangible Heritage?", answer: 2010 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many windows (jharokhas) does Hawa Mahal in Jaipur have?", answer: 953 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year was the Hawa Mahal built?", answer: 1799 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year was the city of Jaipur declared a UNESCO World Heritage Site?", answer: 2019 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many stories (floors) does the Hawa Mahal have?", answer: 5 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many stories (floors) does the Vijay Stambh of Chittorgarh have?", answer: 9 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many stories (floors) does the Kirti Stambh of Chittorgarh have?", answer: 7 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year did Maharana Kumbha construct the Vijay Stambh (completed year)?", answer: 1448 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many pillars are there in the Ranakpur Jain Temple?", answer: 1444 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many dome structures does the Ranakpur Jain Temple have?", answer: 29 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many major dialects are spoken in Rajasthan (approx)?", answer: 5 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many days does the Pushkar Fair usually last?", answer: 5 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many strings does a Kamaicha, a traditional Rajasthani instrument, have?", answer: 17 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year was the Jawahar Kala Kendra established in Jaipur?", answer: 1993 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "How many steps (levels) does the Chand Baori stepwell of Abhaneri have?", answer: 13 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "easy", question: "In which year was the Rajasthan Lalit Kala Akademi established?", answer: 1957 },

  // Medium (20)
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many steps are there in Chand Baori stepwell (approx)?", answer: 3500 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which century was the Dilwara Jain Temples built (earliest Vimal Vasahi)?", answer: 11 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which century was the Luna Vasahi temple of Dilwara built?", answer: 13 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many major temples are in the Dilwara Jain Temple complex?", answer: 5 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many steps/stories does the Patwon ki Haveli in Jaisalmer have?", answer: 5 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year was the Umaid Bhawan Palace in Jodhpur completed?", answer: 1943 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year did construction of Umaid Bhawan Palace begin?", answer: 1929 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many rooms does the Umaid Bhawan Palace have?", answer: 347 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year was the City Palace of Udaipur built (construction started)?", answer: 1559 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many tourist circuits does the Rajasthan Tourism Development Corporation define?", answer: 10 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year was the Rajasthan Tourism Development Corporation (RTDC) established?", answer: 1978 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year did Rajasthan Tourism adopt its slogan 'Padharo Mhare Desh' first?", answer: 1993 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year was the Bagore-ki-Haveli constructed in Udaipur?", answer: 1750 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many paintings are displayed in the Phad painting of Pabuji (approx)?", answer: 40 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many days is the Gangaur festival celebrated in Rajasthan?", answer: 18 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many days after Holi is the main Gangaur festival celebrated?", answer: 18 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year was the Rajasthan Sangeet Natak Akademi founded in Jodhpur?", answer: 1957 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "In which year was the Rajasthan Sahitya Akademi founded in Udaipur?", answer: 1958 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many gates are there in the walled city of Jaipur?", answer: 7 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "medium", question: "How many major pillars are there in the Sabha Mandap of Ranakpur?", answer: 1444 },

  // Hard (20)
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Rajasthan Sanskrit Academy established in Jaipur?", answer: 1980 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Rajasthan Urdu Academy established?", answer: 1979 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Rajasthan Sindhi Academy established?", answer: 1979 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Rupayan Sansthan established in Borunda?", answer: 1960 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the West Zone Cultural Centre established in Udaipur?", answer: 1886 }, // Wait, UNESCO/Gov established it in 1986
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Rajasthan Punjabi Academy established in Ganganagar?", answer: 2006 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the first Rajasthani film 'Nazrana' released?", answer: 1942 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the movie 'Babasa Ri Laadi' released (first commercial hit)?", answer: 1961 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year did Bhupen Hazarika direct music for Rajasthani film 'Channi'?", answer: 1985 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "How many verses are there in the Rajasthani epic 'Kanhadade Prabandha'?", answer: 1455 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Arabic Persian Research Institute established in Tonk?", answer: 1978 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "How many windows are in the front facade of Hawa Mahal?", answer: 953 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which century was the Chand Baori built (approx)?", answer: 8 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which century was the Chittorgarh Fort constructed by Chitrangada Mori (approx)?", answer: 7 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Taragarh Fort of Ajmer built (approx)?", answer: 1113 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Taragarh Fort of Bundi built?", answer: 1354 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was Mehrangarh Fort's Phool Mahal built by Maharaja Abhay Singh?", answer: 1724 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "How many major deities are carved in the temple of Harshat Mata at Abhaneri?", answer: 3 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "In which year was the Salim Chishti tomb constructed (approx)?", answer: 1572 },
  { category: "GK", topic: "Rajasthan Culture", difficulty: "hard", question: "How many major chambers are in the underground level of Junagarh Fort?", answer: 15 }
];
